extends Node

signal language_changed

const LANGUAGE_ZH := "zh"
const LANGUAGE_EN := "en"

var current_language := LANGUAGE_ZH

var translations := {
	LANGUAGE_ZH: {
		"game_title": "命运裂隙",
		"game_subtitle": "Roguelike 卡牌冒险",
		"menu_continue": "继续游戏",
		"menu_new_game": "新游戏",
		"menu_settings": "设置",
		"menu_delete_save": "删除存档",
		"menu_exit": "退出游戏",
		"menu_language_switch": "English",
		"difficulty_title": "选择难度",
		"difficulty_unlocked_max": "最高解锁难度",
		"difficulty_normal": "普通",
		"difficulty_advanced": "进阶",
		"difficulty_hard": "困难",
		"difficulty_nightmare": "噩梦",
		"difficulty_final": "终焉",
		"difficulty_unknown": "未知",
		"difficulty_locked": "未解锁",
		"save_no_adventure": "没有可继续的冒险",
		"save_current_adventure": "当前冒险",
		"save_chapter": "章节",
		"save_difficulty": "难度",
		"save_gold": "金币",
		"save_status": "状态",
		"save_read_failed": "存档读取失败。",
		"save_failed_hint": "你可以删除存档或开始新游戏。",
		"save_completed_hint": "你可以删除存档或开始新游戏。",
		"status_active": "进行中",
		"status_failed": "已失败",
		"status_completed": "已通关",
		"status_no_save": "没有找到可用存档。",
		"status_no_delete_save": "没有可删除的存档。",
		"status_difficulty_locked": "该难度尚未解锁。",
		"status_save_deleted": "存档已删除",
		"status_quit_unsupported": "当前平台不支持直接退出。",
		"dialog_confirm": "确认",
		"dialog_cancel": "取消",
		"dialog_overwrite_title": "覆盖存档",
		"dialog_overwrite_save": "当前已有存档，开始新游戏会覆盖现有存档，是否继续？",
		"dialog_delete_title": "删除存档",
		"dialog_delete_save": "确定要删除当前存档吗？此操作无法撤销。",
		"settings_title": "设置",
		"settings_placeholder": "设置功能开发中\n当前音效系统已可用，后续可在这里加入音量滑条和全屏开关。",
		"settings_back": "返回",
		"chapter_1_name": "第 1 章：森林遗迹",
		"chapter_2_name": "第 2 章：熔火城堡",
		"chapter_3_name": "第 3 章：星界神殿",
		"chapter_4_name": "第 4 章：命运裂隙",
		"chapter_unknown": "未知章节",
		"card.unknown.name": "未知卡牌",
		"relic.unknown.name": "未知遗物",
		"enemy.unknown.name": "敌人",
	},
	LANGUAGE_EN: {
		"game_title": "Fate Rift",
		"game_subtitle": "A Roguelike Card Adventure",
		"menu_continue": "Continue",
		"menu_new_game": "New Game",
		"menu_settings": "Settings",
		"menu_delete_save": "Delete Save",
		"menu_exit": "Quit Game",
		"menu_language_switch": "中文",
		"difficulty_title": "Select Difficulty",
		"difficulty_unlocked_max": "Highest Unlocked",
		"difficulty_normal": "Normal",
		"difficulty_advanced": "Advanced",
		"difficulty_hard": "Hard",
		"difficulty_nightmare": "Nightmare",
		"difficulty_final": "End",
		"difficulty_unknown": "Unknown",
		"difficulty_locked": "Locked",
		"save_no_adventure": "No adventure in progress",
		"save_current_adventure": "Current Adventure",
		"save_chapter": "Chapter",
		"save_difficulty": "Difficulty",
		"save_gold": "Gold",
		"save_status": "Status",
		"save_read_failed": "Failed to read save.",
		"save_failed_hint": "Delete the save or start a new game.",
		"save_completed_hint": "Delete the save or start a new game.",
		"status_active": "In Progress",
		"status_failed": "Failed",
		"status_completed": "Completed",
		"status_no_save": "No available save found.",
		"status_no_delete_save": "No save to delete.",
		"status_difficulty_locked": "This difficulty is locked.",
		"status_save_deleted": "Save deleted",
		"status_quit_unsupported": "This platform cannot quit directly.",
		"dialog_confirm": "Confirm",
		"dialog_cancel": "Cancel",
		"dialog_overwrite_title": "Overwrite Save",
		"dialog_overwrite_save": "A save already exists. Starting a new game will overwrite it. Continue?",
		"dialog_delete_title": "Delete Save",
		"dialog_delete_save": "Are you sure you want to delete the current save? This cannot be undone.",
		"settings_title": "Settings",
		"settings_placeholder": "Settings are under development\nThe sound system is available. Volume sliders and fullscreen options can be added here later.",
		"settings_back": "Back",
		"chapter_1_name": "Chapter 1: Forest Ruins",
		"chapter_2_name": "Chapter 2: Molten Castle",
		"chapter_3_name": "Chapter 3: Astral Temple",
		"chapter_4_name": "Chapter 4: Fate Rift",
		"chapter_unknown": "Unknown Chapter",
		"card.unknown.name": "Unknown Card",
		"relic.unknown.name": "Unknown Relic",
		"enemy.unknown.name": "Enemy",
	},
}


func _ready() -> void:
	_install_content_translations()
	load_language_from_profile()


func set_language(lang: String) -> void:
	var normalized := _normalize_language(lang)
	if current_language == normalized:
		return
	current_language = normalized
	save_language_to_profile()
	language_changed.emit()


func get_language() -> String:
	return current_language


func toggle_language() -> void:
	set_language(LANGUAGE_EN if current_language == LANGUAGE_ZH else LANGUAGE_ZH)


func tr_key(key: String) -> String:
	var language_table: Dictionary = translations.get(current_language, {})
	if language_table.has(key):
		return str(language_table[key])

	var fallback_table: Dictionary = translations.get(LANGUAGE_ZH, {})
	if fallback_table.has(key):
		push_warning("[LanguageManager] missing key for %s: %s" % [current_language, key])
		return str(fallback_table[key])

	push_warning("[LanguageManager] missing translation key: " + key)
	return key


func tr_format(key: String, params: Dictionary) -> String:
	var text := tr_key(key)
	for param_key in params.keys():
		text = text.replace("{%s}" % str(param_key), str(params[param_key]))
	return text


func has_key(key: String) -> bool:
	var language_table: Dictionary = translations.get(current_language, {})
	var fallback_table: Dictionary = translations.get(LANGUAGE_ZH, {})
	return language_table.has(key) or fallback_table.has(key)


func get_card_name(card_id: String, upgraded := false, fallback := "") -> String:
	var base := _entity_text("card.%s.name" % card_id, fallback if fallback != "" else card_id)
	return base + "+" if upgraded else base


func get_card_description(card_id: String, upgraded := false, fallback := "") -> String:
	var key := "card.%s.upgraded_desc" % card_id if upgraded else "card.%s.desc" % card_id
	return _entity_text(key, fallback)


func get_relic_name(relic_id: String, fallback := "") -> String:
	return _entity_text("relic.%s.name" % relic_id, fallback if fallback != "" else relic_id)


func get_relic_description(relic_id: String, fallback := "") -> String:
	return _entity_text("relic.%s.desc" % relic_id, fallback)


func get_enemy_name(enemy_id: String, fallback := "") -> String:
	return _entity_text("enemy.%s.name" % enemy_id, fallback if fallback != "" else enemy_id)


func get_event_title(event_id: String, fallback := "") -> String:
	return _entity_text("event.%s.title" % event_id, fallback if fallback != "" else event_id)


func get_status_name(status_id: String, fallback := "") -> String:
	return _entity_text("status.%s.name" % status_id, fallback if fallback != "" else status_id)


func _entity_text(key: String, fallback: String) -> String:
	var language_table: Dictionary = translations.get(current_language, {})
	if language_table.has(key):
		return str(language_table[key])

	var zh_table: Dictionary = translations.get(LANGUAGE_ZH, {})
	if current_language == LANGUAGE_ZH and zh_table.has(key):
		return str(zh_table[key])

	if fallback != "":
		return fallback

	push_warning("[LanguageManager] missing translation key: " + key)
	return key


func load_language_from_profile() -> void:
	var save_manager := get_node_or_null("/root/SaveManager")
	if save_manager != null and save_manager.has_method("get_profile_language"):
		current_language = _normalize_language(save_manager.get_profile_language())
	else:
		current_language = LANGUAGE_ZH


func save_language_to_profile() -> void:
	var save_manager := get_node_or_null("/root/SaveManager")
	if save_manager != null and save_manager.has_method("set_profile_language"):
		save_manager.set_profile_language(current_language)


func _normalize_language(lang: String) -> String:
	if lang == LANGUAGE_EN:
		return LANGUAGE_EN
	return LANGUAGE_ZH


func _install_content_translations() -> void:
	_add_translations(LANGUAGE_ZH, {
		"ui_confirm": "确认",
		"ui_cancel": "取消",
		"ui_back": "返回",
		"ui_continue": "继续",
		"ui_close": "关闭",
		"ui_gold": "金币",
		"ui_hp": "生命",
		"ui_block": "护甲",
		"ui_energy": "能量",
		"ui_status": "状态",
		"ui_cost": "费用",
		"ui_relics": "遗物",
		"ui_none": "无",
		"ui_type": "类型",
		"ui_settings": "设置",
		"ui_locked": "未解锁",
		"battle_hp": "生命：{current} / {max}",
		"battle_block": "护甲：{value}",
		"battle_energy": "能量：{current} / {max}",
		"battle_player_turn": "玩家回合",
		"battle_start": "战斗开始。",
		"battle_enemy_turn": "敌人回合",
		"battle_turn_count": "第 {turn} 回合｜{phase}",
		"battle_end_turn": "结束回合",
		"battle_view_deck": "查看牌组",
		"battle_return_main_menu": "返回主菜单",
		"battle_draw_pile": "抽牌堆",
		"battle_discard_pile": "弃牌堆",
		"battle_exhaust_pile": "消耗",
		"battle_hand_count": "手牌",
		"battle_intent": "意图：{intent}",
		"battle_intent_attack": "攻击 {value}",
		"battle_intent_attack_hits": "攻击 {value} x{hits}",
		"battle_intent_strong_attack": "强力攻击 {value}",
		"battle_intent_defend": "防御 {value}",
		"battle_intent_buff": "强化 {value}",
		"battle_intent_weak": "施加虚弱",
		"battle_intent_burn": "施加燃烧",
		"battle_intent_charge": "正在蓄力",
		"battle_intent_heal": "治疗 {value}",
		"battle_intent_unknown": "未知",
		"battle_turn_draw": "第 {turn} 回合开始，抽 {draw} 张牌。",
		"battle_hand_full_no_draw": "手牌上限已满，未抽取 {count} 张牌。",
		"battle_overflow_destroy": "手牌已满，摧毁 {count} 张溢出的牌。",
		"battle_not_enough_energy": "{card} 的能量不足。",
		"battle_play_card": "打出 {card}",
		"status.burn.name": "燃烧",
		"status.weak.name": "虚弱",
		"status.strength.name": "力量",
		"status.block.name": "护甲",
		"map_title": "路线地图",
		"map_node_normal_battle": "普通战斗",
		"map_node_elite_battle": "精英战斗",
		"map_node_boss_battle": "Boss 战",
		"map_node_event": "事件",
		"map_node_shop": "商店",
		"map_node_rest": "休息",
		"map_node_relic_reward": "遗物",
		"map_node_special_reward": "特殊牌",
		"map_return_main_menu": "返回主菜单",
		"shop_title": "商店",
		"shop_pack_title": "卡包抽取",
		"shop_goods_title": "商品",
		"shop_buy": "购买",
		"shop_bought": "已购买",
		"shop_not_enough_gold": "金币不足",
		"shop_tarot_pack": "塔罗秘匣",
		"shop_relic_pack": "遗物宝箱",
		"shop_edit_deck": "编辑卡组",
		"shop_tarot_desc": "随机获得 1 张未拥有的特殊卡牌",
		"shop_tarot_all_collected": "你已经收集了所有特殊卡牌",
		"shop_relic_desc": "随机获得 1 个未拥有的遗物",
		"shop_relic_all_collected": "你已经收集了所有遗物",
		"shop_pack_draw": "抽取",
		"shop_pack_open": "开启",
		"shop_relic_title": "遗物",
		"shop_no_relic_for_sale": "暂无可购买遗物",
		"shop_price_format": "价格：{price} 金币",
		"shop_gold_format": "金币：{gold}",
		"shop_obtained_special_card": "获得特殊卡牌：{card}",
		"shop_obtained_relic": "获得遗物：{relic}",
		"shop_buy_card_result": "购买卡牌：{card}",
		"shop_buy_relic_result": "购买遗物：{relic}",
		"shop_product_missing": "商品不存在",
		"shop_relic_missing": "遗物不存在",
		"shop_relic_already_owned": "已经拥有这个遗物",
		"shop_no_relic_available": "没有可获得的遗物",
		"deckbuilder_collection_title": "我的卡牌",
		"deckbuilder_detail_title": "卡牌详情",
		"deckbuilder_current_deck": "当前卡组",
		"deckbuilder_title_new": "选择初始卡组",
		"deckbuilder_title_edit": "编辑当前卡组",
		"deckbuilder_confirm": "确认卡组",
		"deckbuilder_save_return": "保存并返回",
		"deckbuilder_cancel_edit": "取消编辑",
		"deckbuilder_add": "加入卡组",
		"deckbuilder_remove_one": "移除 1 张",
		"deckbuilder_select_card": "选择一张卡牌",
		"deckbuilder_detail_hint": "点击左侧卡牌查看详情。",
		"deckbuilder_stats": "总卡牌 {total}/{required_total}｜基础牌 {basic}/{required_basic}｜特殊牌 {special}/{required_special}",
		"deckbuilder_type_line": "类型：{type} / {category}",
		"deckbuilder_rarity_line": "稀有度：{rarity}",
		"deckbuilder_owned_count": "拥有：{count}",
		"deckbuilder_selected_count": "已加入：{count}",
		"deckbuilder_category_basic": "基础",
		"deckbuilder_category_special": "特殊",
		"deckbuilder_editing_shop_hint": "正在商店中编辑卡组，编辑完成后将返回商店。",
		"deckbuilder_editing_rest_hint": "正在休息点中编辑卡组，编辑完成后将返回休息点。",
		"deckbuilder_editing_return_hint": "编辑完成后将返回当前页面。",
		"deckbuilder_error_total_low": "当前牌组不足 20 张",
		"deckbuilder_error_total_high": "当前牌组超过 20 张",
		"deckbuilder_error_total_full": "当前牌组已经达到 20 张",
		"deckbuilder_error_basic_count": "基础牌必须选择 16 张",
		"deckbuilder_error_special_count": "特殊牌必须选择 4 张",
		"deckbuilder_error_not_owned": "你没有拥有这张卡牌",
		"deckbuilder_error_special_duplicate": "特殊牌【{card}】不能重复",
		"deckbuilder_error_basic_max": "基础牌【{card}】最多只能放 3 张",
		"deckbuilder_error_owned_limit": "选择数量超过拥有数量",
		"deckbuilder_error_card_not_in_deck": "当前卡组中没有这张牌",
		"deckbuilder_error_special_full": "特殊牌最多只能选择 4 张",
		"deckbuilder_error_basic_full": "基础牌最多只能选择 16 张",
		"deckbuilder_error_unknown_category": "未知卡牌分类",
		"rarity.common": "普通",
		"rarity.uncommon": "稀有",
		"rarity.rare": "史诗",
		"chapter_reward_title": "章节通关奖励",
		"chapter_reward_none_pending": "当前没有待领取的章节奖励。",
		"chapter_reward_already_claimed": "已选择奖励，请继续。",
		"chapter_reward_status": "生命：{hp} / {max_hp}　金币：{gold}　命运：{fate}",
		"chapter_reward_selected": "已选择奖励：{reward}\n{result}",
		"chapter_reward.reward": "奖励",
		"chapter_reward.gold.name": "丰厚战利品",
		"chapter_reward.gold.desc": "获得 150 金币。",
		"chapter_reward.relic.name": "古老遗物",
		"chapter_reward.relic.desc": "获得 1 个随机遗物。",
		"chapter_reward.special_card.name": "塔罗秘匣",
		"chapter_reward.special_card.desc": "获得 1 张未拥有的特殊卡牌。",
		"chapter_reward.max_hp.name": "生命祝福",
		"chapter_reward.max_hp.desc": "最大生命值提高 15，并恢复 15 点生命。",
		"chapter_reward.upgrade_two.name": "锻造机会",
		"chapter_reward.upgrade_two.desc": "随机强化 2 张未升级基础牌。",
		"chapter_reward.remove_basic.name": "净化牌组",
		"chapter_reward.remove_basic.desc": "移除 1 张基础牌。",
		"chapter_reward.fate_ember.name": "命运余烬",
		"chapter_reward.fate_ember.desc": "战斗失败时自动消耗，满血复活并重新挑战当前关卡。",
		"chapter_reward.supply.name": "全面补给",
		"chapter_reward.supply.desc": "恢复全部生命，并获得 80 金币。",
		"chapter_reward.gold_fallback.name": "金币补偿",
		"chapter_reward.gold_fallback.desc": "获得 {amount} 金币。",
		"chapter_reward.result_gold": "获得 {amount} 金币。",
		"chapter_reward.result_max_hp": "最大生命值 +{amount}，恢复 {amount} 点生命。",
		"chapter_reward.result_fallback_gold": "改为获得 {amount} 金币。",
		"chapter_reward.result_upgrade": "已强化：{cards}。",
		"chapter_reward.result_remove": "已移除：{card}。",
		"chapter_reward.result_relic": "获得遗物：{relic}。",
		"chapter_reward.result_supply": "恢复全部生命，并获得 {amount} 金币。",
		"chapter_reward.result_no_effect": "没有效果。",
		"chapter_reward.result_special_card": "获得特殊卡牌：{card}。",
		"chapter_reward.subtitle_ch1": "第 1 章通关：森林遗迹已通关",
		"chapter_reward.subtitle_ch2": "第 2 章通关：熔火城堡已通关",
		"chapter_reward.subtitle_ch3": "第 3 章通关：星界神殿已通关",
		"chapter_reward.subtitle_default": "章节已通关",
		"rest_title": "休息点",
		"rest_heal": "休息恢复",
		"rest_upgrade": "强化卡牌",
		"rest_edit_deck": "编辑卡组",
		"reward_battle_title": "战斗奖励",
		"reward_relic_title": "获得遗物",
		"ending.defeat.title": "冒险失败",
		"ending.defeat.desc": "你倒在了这场战斗中。",
		"ending.defeat.summary": "本次难度：{difficulty}\n章节：第 {chapter} 章\n金币：{gold}\n获得遗物：{relics}\n当前卡组：{cards} 张",
		"ending.normal.title": "通关成功",
		"ending.normal.desc": "你击败了世界吞噬者，完成了这次冒险。",
		"ending.star.title": "星辰结局",
		"ending.star.desc": "你没有摧毁命运，而是选择接纳它。星辰重新排列，世界从崩塌边缘被拉回。",
		"ending.abyss.title": "深渊结局",
		"ending.abyss.desc": "你夺取了命运的权柄，但深渊也回应了你的欲望。世界得救了，还是换了一个主人？",
		"ending.summary": "本次难度：{difficulty}\n{unlock}\n当前最高解锁难度：{max_difficulty}\n最终金币：{gold}\n获得遗物：{relics}\n当前卡组：{cards} 张\n命运分数：{fate}",
	})

	_add_translations(LANGUAGE_EN, {
		"ui_confirm": "Confirm",
		"ui_cancel": "Cancel",
		"ui_back": "Back",
		"ui_continue": "Continue",
		"ui_close": "Close",
		"ui_gold": "Gold",
		"ui_hp": "HP",
		"ui_block": "Block",
		"ui_energy": "Energy",
		"ui_status": "Status",
		"ui_cost": "Cost",
		"ui_relics": "Relics",
		"ui_none": "None",
		"ui_type": "Type",
		"ui_settings": "Settings",
		"ui_locked": "Locked",
		"battle_hp": "HP: {current} / {max}",
		"battle_block": "Block: {value}",
		"battle_energy": "Energy: {current} / {max}",
		"battle_player_turn": "Player Turn",
		"battle_start": "Battle started.",
		"battle_enemy_turn": "Enemy Turn",
		"battle_turn_count": "Turn {turn} | {phase}",
		"battle_end_turn": "End Turn",
		"battle_view_deck": "View Deck",
		"battle_return_main_menu": "Main Menu",
		"battle_draw_pile": "Draw Pile",
		"battle_discard_pile": "Discard Pile",
		"battle_exhaust_pile": "Exhaust",
		"battle_hand_count": "Hand",
		"battle_intent": "Intent: {intent}",
		"battle_intent_attack": "Attack {value}",
		"battle_intent_attack_hits": "Attack {value} x{hits}",
		"battle_intent_strong_attack": "Strong Attack {value}",
		"battle_intent_defend": "Defend {value}",
		"battle_intent_buff": "Buff {value}",
		"battle_intent_weak": "Apply Weak",
		"battle_intent_burn": "Apply Burn",
		"battle_intent_charge": "Charging",
		"battle_intent_heal": "Heal {value}",
		"battle_intent_unknown": "Unknown",
		"battle_turn_draw": "Turn {turn} begins. Draw {draw} card(s).",
		"battle_hand_full_no_draw": "Hand is full. {count} card(s) were not drawn.",
		"battle_overflow_destroy": "Hand is full. Destroyed {count} overflow card(s).",
		"battle_not_enough_energy": "Not enough energy for {card}.",
		"battle_play_card": "Played {card}",
		"status.burn.name": "Burn",
		"status.weak.name": "Weak",
		"status.strength.name": "Strength",
		"status.block.name": "Block",
		"map_title": "Route Map",
		"map_node_normal_battle": "Battle",
		"map_node_elite_battle": "Elite",
		"map_node_boss_battle": "Boss",
		"map_node_event": "Event",
		"map_node_shop": "Shop",
		"map_node_rest": "Rest",
		"map_node_relic_reward": "Relic",
		"map_node_special_reward": "Special",
		"map_return_main_menu": "Main Menu",
		"shop_title": "Shop",
		"shop_pack_title": "Packs",
		"shop_goods_title": "Goods",
		"shop_buy": "Buy",
		"shop_bought": "Bought",
		"shop_not_enough_gold": "Not enough gold",
		"shop_tarot_pack": "Tarot Coffer",
		"shop_relic_pack": "Relic Chest",
		"shop_edit_deck": "Edit Deck",
		"shop_tarot_desc": "Gain 1 unowned special card at random",
		"shop_tarot_all_collected": "You have collected all special cards",
		"shop_relic_desc": "Gain 1 unowned relic at random",
		"shop_relic_all_collected": "You have collected all relics",
		"shop_pack_draw": "Draw",
		"shop_pack_open": "Open",
		"shop_relic_title": "Relic",
		"shop_no_relic_for_sale": "No relic available",
		"shop_price_format": "Price: {price} Gold",
		"shop_gold_format": "Gold: {gold}",
		"shop_obtained_special_card": "Obtained special card: {card}",
		"shop_obtained_relic": "Obtained relic: {relic}",
		"shop_buy_card_result": "Bought card: {card}",
		"shop_buy_relic_result": "Bought relic: {relic}",
		"shop_product_missing": "Product not found",
		"shop_relic_missing": "Relic not found",
		"shop_relic_already_owned": "You already own this relic",
		"shop_no_relic_available": "No relic available",
		"deckbuilder_collection_title": "My Cards",
		"deckbuilder_detail_title": "Card Details",
		"deckbuilder_current_deck": "Current Deck",
		"deckbuilder_title_new": "Choose Starting Deck",
		"deckbuilder_title_edit": "Edit Current Deck",
		"deckbuilder_confirm": "Confirm Deck",
		"deckbuilder_save_return": "Save and Return",
		"deckbuilder_cancel_edit": "Cancel Editing",
		"deckbuilder_add": "Add to Deck",
		"deckbuilder_remove_one": "Remove 1",
		"deckbuilder_select_card": "Select a Card",
		"deckbuilder_detail_hint": "Select a card on the left to view details.",
		"deckbuilder_stats": "Total {total}/{required_total} | Basic {basic}/{required_basic} | Special {special}/{required_special}",
		"deckbuilder_type_line": "Type: {type} / {category}",
		"deckbuilder_rarity_line": "Rarity: {rarity}",
		"deckbuilder_owned_count": "Owned: {count}",
		"deckbuilder_selected_count": "Selected: {count}",
		"deckbuilder_category_basic": "Basic",
		"deckbuilder_category_special": "Special",
		"deckbuilder_editing_shop_hint": "Editing your deck in the shop. You will return to the shop when finished.",
		"deckbuilder_editing_rest_hint": "Editing your deck at the rest site. You will return to the rest site when finished.",
		"deckbuilder_editing_return_hint": "You will return to the current page when finished.",
		"deckbuilder_error_total_low": "Your deck has fewer than 20 cards",
		"deckbuilder_error_total_high": "Your deck has more than 20 cards",
		"deckbuilder_error_total_full": "Your deck already has 20 cards",
		"deckbuilder_error_basic_count": "You must choose exactly 16 Basic cards",
		"deckbuilder_error_special_count": "You must choose exactly 4 Special cards",
		"deckbuilder_error_not_owned": "You do not own this card",
		"deckbuilder_error_special_duplicate": "Special card {card} cannot be duplicated",
		"deckbuilder_error_basic_max": "Basic card {card} can have at most 3 copies",
		"deckbuilder_error_owned_limit": "Selected count exceeds owned count",
		"deckbuilder_error_card_not_in_deck": "This card is not in the current deck",
		"deckbuilder_error_special_full": "You can choose at most 4 Special cards",
		"deckbuilder_error_basic_full": "You can choose at most 16 Basic cards",
		"deckbuilder_error_unknown_category": "Unknown card category",
		"rarity.common": "Common",
		"rarity.uncommon": "Uncommon",
		"rarity.rare": "Rare",
		"chapter_reward_title": "Chapter Clear Reward",
		"chapter_reward_none_pending": "There is no chapter reward to claim.",
		"chapter_reward_already_claimed": "Reward selected. Continue when ready.",
		"chapter_reward_status": "HP: {hp} / {max_hp}  Gold: {gold}  Fate: {fate}",
		"chapter_reward_selected": "Selected reward: {reward}\n{result}",
		"chapter_reward.reward": "Reward",
		"chapter_reward.gold.name": "Rich Spoils",
		"chapter_reward.gold.desc": "Gain 150 Gold.",
		"chapter_reward.relic.name": "Ancient Relic",
		"chapter_reward.relic.desc": "Gain 1 random relic.",
		"chapter_reward.special_card.name": "Tarot Coffer",
		"chapter_reward.special_card.desc": "Gain 1 unowned special card.",
		"chapter_reward.max_hp.name": "Life Blessing",
		"chapter_reward.max_hp.desc": "Increase max HP by 15 and heal 15 HP.",
		"chapter_reward.upgrade_two.name": "Forge Opportunity",
		"chapter_reward.upgrade_two.desc": "Randomly upgrade 2 unupgraded Basic cards.",
		"chapter_reward.remove_basic.name": "Purify Deck",
		"chapter_reward.remove_basic.desc": "Remove 1 Basic card.",
		"chapter_reward.fate_ember.name": "Fate Ember",
		"chapter_reward.fate_ember.desc": "When you fall in battle, revive at full HP and retry the current encounter.",
		"chapter_reward.supply.name": "Full Supply",
		"chapter_reward.supply.desc": "Fully heal and gain 80 Gold.",
		"chapter_reward.gold_fallback.name": "Gold Compensation",
		"chapter_reward.gold_fallback.desc": "Gain {amount} Gold.",
		"chapter_reward.result_gold": "Gained {amount} Gold.",
		"chapter_reward.result_max_hp": "Max HP +{amount}. Healed {amount} HP.",
		"chapter_reward.result_fallback_gold": "Converted into {amount} Gold.",
		"chapter_reward.result_upgrade": "Upgraded: {cards}.",
		"chapter_reward.result_remove": "Removed: {card}.",
		"chapter_reward.result_relic": "Gained relic: {relic}.",
		"chapter_reward.result_supply": "Fully healed and gained {amount} Gold.",
		"chapter_reward.result_no_effect": "No effect.",
		"chapter_reward.result_special_card": "Gained special card: {card}.",
		"chapter_reward.subtitle_ch1": "Chapter 1 cleared: Forest Ruins",
		"chapter_reward.subtitle_ch2": "Chapter 2 cleared: Molten Castle",
		"chapter_reward.subtitle_ch3": "Chapter 3 cleared: Astral Temple",
		"chapter_reward.subtitle_default": "Chapter cleared",
		"rest_title": "Rest Site",
		"rest_heal": "Rest",
		"rest_upgrade": "Upgrade Card",
		"rest_edit_deck": "Edit Deck",
		"reward_battle_title": "Battle Reward",
		"reward_relic_title": "Relic Reward",
		"ending.defeat.title": "Adventure Failed",
		"ending.defeat.desc": "You fell in battle.",
		"ending.defeat.summary": "Difficulty: {difficulty}\nChapter: {chapter}\nGold: {gold}\nRelics: {relics}\nDeck: {cards} cards",
		"ending.normal.title": "Victory",
		"ending.normal.desc": "You defeated the World Devourer and completed this adventure.",
		"ending.star.title": "Starlight Ending",
		"ending.star.desc": "You did not destroy fate. You accepted it. The stars realign, pulling the world back from the edge of collapse.",
		"ending.abyss.title": "Abyss Ending",
		"ending.abyss.desc": "You seized the authority of fate, but the abyss answered your desire. Was the world saved, or merely given a new master?",
		"ending.summary": "Difficulty: {difficulty}\n{unlock}\nHighest Unlocked: {max_difficulty}\nFinal Gold: {gold}\nRelics: {relics}\nDeck: {cards} cards\nFate Score: {fate}",
	})

	_install_card_translations()
	_install_relic_translations()
	_install_enemy_translations()
	_install_remaining_ui_translations()
	_install_localization_gap_translations()


func _add_translations(language: String, entries: Dictionary) -> void:
	if not translations.has(language):
		translations[language] = {}
	for key in entries.keys():
		translations[language][key] = entries[key]


func _install_remaining_ui_translations() -> void:
	_add_translations(LANGUAGE_ZH, {
		"ui_unknown": "未知",
		"map_chapter_progress": "进度 {floor} / {max}　难度：{difficulty}　生命：{hp} / {max_hp}　金币：{gold}",
		"chapter.1.name": "第 1 章：森林遗迹",
		"chapter.2.name": "第 2 章：熔火城堡",
		"chapter.3.name": "第 3 章：星界神殿",
		"chapter.4.name": "第 4 章：命运裂隙",
		"chapter.4.star.name": "第 4 章：命运裂隙",
		"chapter.4.abyss.name": "第 4 章：命运裂隙",
		"card_type.attack": "攻击",
		"card_type.skill": "技能",
		"card_type.power": "能力",
		"chapter4_intro.star.title": "星辰之路",
		"chapter4_intro.star.body": "世界吞噬者倒下后，星界神殿并未崩塌。\n\n天空中破碎的星图开始缓慢重组，银白色的命运丝线从虚空中垂落，连接起那些早已断裂的道路。\n\n你曾在星辰低语中接受了命运的指引。\n\n如今，星辰回应了你的选择。\n\n一条通往命运裂隙深处的道路在光中显现。那里没有逃避，也没有反抗，只有最终的审判与归位。\n\n你将接纳命运，让世界回归星辰秩序。",
		"chapter4_intro.star.button": "继续前往命运裂隙",
		"chapter4_intro.abyss.title": "深渊回应",
		"chapter4_intro.abyss.body": "世界吞噬者倒下后，星界神殿陷入死寂。\n\n可就在星光即将熄灭的瞬间，你灵魂深处的契约开始燃烧。黑色灰烬从掌心升起，像无数断裂的命运丝线重新缠上你的身体。\n\n你曾签下深渊契约，试图夺取命运的权柄。\n\n如今，深渊回应了你的欲望。\n\n一道不应存在的裂隙在神殿尽头张开，里面传来低沉的呼唤。那不是救赎，而是一场交换。\n\n你将夺取命运，但也必须承受深渊的代价。",
		"chapter4_intro.abyss.button": "回应深渊",
	})
	_add_translations(LANGUAGE_EN, {
		"ui_unknown": "Unknown",
		"map_chapter_progress": "Progress {floor} / {max}   Difficulty: {difficulty}   HP: {hp} / {max_hp}   Gold: {gold}",
		"chapter.1.name": "Chapter 1: Forest Ruins",
		"chapter.2.name": "Chapter 2: Molten Castle",
		"chapter.3.name": "Chapter 3: Astral Temple",
		"chapter.4.name": "Chapter 4: Fate Rift",
		"chapter.4.star.name": "Chapter 4: Fate Rift - Starlight Path",
		"chapter.4.abyss.name": "Chapter 4: Fate Rift - Abyss Path",
		"card_type.attack": "Attack",
		"card_type.skill": "Skill",
		"card_type.power": "Power",
		"chapter4_intro.star.title": "Starlight Path",
		"chapter4_intro.star.body": "After the World Devourer falls, the Astral Temple does not collapse.\n\nThe shattered star map begins to rebuild itself. Silver threads of fate descend from the void, joining roads that had long been severed.\n\nYou once accepted the guidance of the stars through their quiet whisper.\n\nNow the stars answer your choice.\n\nA road into the depths of the Fate Rift appears in the light. There is no escape and no rebellion there, only final judgment and return.\n\nYou will accept fate and restore the world to the order of the stars.",
		"chapter4_intro.star.button": "Continue to the Fate Rift",
		"chapter4_intro.abyss.title": "The Abyss Answers",
		"chapter4_intro.abyss.body": "After the World Devourer falls, the Astral Temple sinks into silence.\n\nAs the last starlight begins to fade, the contract in the depths of your soul starts to burn. Black ash rises from your palm, wrapping around you like countless broken threads of fate.\n\nYou once signed the abyssal contract, seeking to seize the authority of fate.\n\nNow the abyss answers your desire.\n\nA rift that should not exist opens at the far end of the temple, and a low call echoes from within. It is not salvation, but an exchange.\n\nYou will take fate for yourself, but you must bear the price of the abyss.",
		"chapter4_intro.abyss.button": "Answer the Abyss",
	})


func _install_card_translations() -> void:
	_add_translations(LANGUAGE_ZH, {
		"card.basic_strike.name": "打击",
		"card.basic_strike.desc": "造成 4 点伤害。",
		"card.basic_strike.upgraded_desc": "造成 9 点伤害。",
		"card.basic_heavy_blow.name": "重击",
		"card.basic_heavy_blow.desc": "造成 8 点伤害。",
		"card.basic_heavy_blow.upgraded_desc": "造成 16 点伤害。",
		"card.basic_combo_strike.name": "连击",
		"card.basic_combo_strike.desc": "造成 3 点伤害两次。",
		"card.basic_combo_strike.upgraded_desc": "造成 4 点伤害两次。",
		"card.basic_flame_slash.name": "火焰斩",
		"card.basic_flame_slash.desc": "造成 6 点伤害，并施加 3 层燃烧。",
		"card.basic_flame_slash.upgraded_desc": "造成 8 点伤害，并施加 3 层燃烧。",
		"card.basic_armor_break.name": "破甲击",
		"card.basic_armor_break.desc": "造成 6 点伤害，并施加 2 层虚弱。",
		"card.basic_armor_break.upgraded_desc": "造成 7 点伤害，并施加 2 层虚弱。",
		"card.basic_guard.name": "格挡",
		"card.basic_guard.desc": "获得 5 点护甲。",
		"card.basic_guard.upgraded_desc": "获得 8 点护甲。",
		"card.basic_hold_fast.name": "坚守",
		"card.basic_hold_fast.desc": "获得 12 点护甲。",
		"card.basic_hold_fast.upgraded_desc": "获得 16 点护甲。",
		"card.basic_nimble_defense.name": "灵巧防御",
		"card.basic_nimble_defense.desc": "获得 4 点护甲，抽 1 张牌。",
		"card.basic_nimble_defense.upgraded_desc": "获得 7 点护甲，抽 1 张牌。",
		"card.basic_counter_stance.name": "反击姿态",
		"card.basic_counter_stance.desc": "获得 6 点护甲，并造成 3 点伤害。",
		"card.basic_counter_stance.upgraded_desc": "获得 9 点护甲，并造成 5 点伤害。",
		"card.basic_iron_wall.name": "铁壁",
		"card.basic_iron_wall.desc": "获得 20 点护甲。",
		"card.basic_iron_wall.upgraded_desc": "获得 28 点护甲。",
		"card.basic_charge.name": "充能",
		"card.basic_charge.desc": "获得 1 点能量。",
		"card.basic_charge.upgraded_desc": "获得 2 点能量。",
		"card.basic_insight.name": "洞察",
		"card.basic_insight.desc": "抽 2 张牌。",
		"card.basic_insight.upgraded_desc": "抽 3 张牌。",
		"card.basic_tactical_shift.name": "战术调整",
		"card.basic_tactical_shift.desc": "抽 3 张牌。",
		"card.basic_tactical_shift.upgraded_desc": "抽 2 张牌。",
		"card.basic_burning_mark.name": "燃烧印记",
		"card.basic_burning_mark.desc": "施加 4 层燃烧。",
		"card.basic_burning_mark.upgraded_desc": "施加 6 层燃烧。",
		"card.basic_weaken.name": "削弱",
		"card.basic_weaken.desc": "施加 4 层虚弱。",
		"card.basic_weaken.upgraded_desc": "施加 3 层虚弱。",
		"card.basic_grace.name": "恩典",
		"card.basic_grace.desc": "回复 8 点生命。",
		"card.basic_restore.name": "恢复",
		"card.basic_restore.desc": "回复 5 点生命。",
		"card.basic_quick_cut.name": "快速斩",
		"card.basic_quick_cut.desc": "造成 3 点伤害。",
		"card.basic_quick_cut.upgraded_desc": "造成 5 点伤害。",
		"card.basic_dual_cut.name": "双刃斩",
		"card.basic_dual_cut.desc": "造成 4 点伤害两次。",
		"card.basic_dual_cut.upgraded_desc": "造成 5 点伤害两次。",
		"card.basic_guarded_strike.name": "守势打击",
		"card.basic_guarded_strike.desc": "造成 5 点伤害，获得 3 点护甲。",
		"card.basic_guarded_strike.upgraded_desc": "造成 7 点伤害，获得 5 点护甲。",
		"card.basic_guard_up.name": "架盾",
		"card.basic_guard_up.desc": "获得 3 点护甲。",
		"card.basic_guard_up.upgraded_desc": "获得 5 点护甲。",
		"card.basic_battle_focus.name": "战斗专注",
		"card.basic_battle_focus.desc": "抽 1 张牌，获得 1 点能量。",
		"card.basic_battle_focus.upgraded_desc": "抽 2 张牌，获得 1 点能量。",
		"card.basic_prepare.name": "准备",
		"card.basic_prepare.desc": "抽 1 张牌，然后弃 1 张牌。",
		"card.basic_prepare.upgraded_desc": "抽 2 张牌，然后弃 1 张牌。",
		"card.basic_cleanse.name": "净化",
		"card.basic_cleanse.desc": "移除自身 1 层虚弱或燃烧，获得 4 点护甲。",
		"card.basic_cleanse.upgraded_desc": "移除自身 1 层虚弱和 1 层燃烧，获得 6 点护甲。",
		"card.basic_warm_blood.name": "热血",
		"card.basic_warm_blood.desc": "回复 3 点生命，获得 1 点能量。",
		"card.basic_warm_blood.upgraded_desc": "回复 5 点生命，获得 1 点能量。",
		"card.basic_suppress.name": "压制",
		"card.basic_suppress.desc": "施加 1 层虚弱。如果敌人有护甲，额外施加 1 层虚弱。",
		"card.basic_suppress.upgraded_desc": "施加 2 层虚弱。如果敌人有护甲，额外施加 1 层虚弱。",
		"card.basic_kindling.name": "引燃",
		"card.basic_kindling.desc": "施加 2 层燃烧。若目标没有燃烧，改为施加 4 层燃烧。",
		"card.basic_kindling.upgraded_desc": "施加 3 层燃烧。若目标没有燃烧，改为施加 5 层燃烧。",
		"card.basic_flame_guard.name": "火焰护势",
		"card.basic_flame_guard.desc": "获得 8 点护甲，并施加 2 层燃烧。",
		"card.basic_flame_guard.upgraded_desc": "获得 11 点护甲，并施加 3 层燃烧。",
		"card.basic_soul_spark.name": "灵魂火花",
		"card.basic_soul_spark.desc": "造成 2 点伤害，抽 1 张牌。",
		"card.basic_soul_spark.upgraded_desc": "造成 3 点伤害，抽 1 张牌，获得 1 点护甲。",
		"card.basic_burning_edge.name": "灼刃",
		"card.basic_burning_edge.desc": "造成 5 点伤害。如果目标已有燃烧，额外造成 3 点伤害。",
		"card.basic_burning_edge.upgraded_desc": "造成 7 点伤害。如果目标已有燃烧，额外造成 5 点伤害。",
		"card.basic_cinder_strike.name": "余烬击",
		"card.basic_cinder_strike.desc": "造成 9 点伤害。若目标有燃烧，施加 2 层虚弱。",
		"card.basic_cinder_strike.upgraded_desc": "造成 12 点伤害。若目标有燃烧，施加 3 层虚弱。",
		"card.basic_execution.name": "处决",
		"card.basic_execution.desc": "造成 10 点伤害。若敌人生命低于 50%，额外造成 6 点伤害。",
		"card.basic_execution.upgraded_desc": "造成 13 点伤害。若敌人生命低于 50%，额外造成 8 点伤害。",
		"card.basic_last_stand.name": "背水一战",
		"card.basic_last_stand.desc": "获得 8 点护甲。若你的生命低于 50%，额外获得 8 点护甲。",
		"card.basic_last_stand.upgraded_desc": "获得 10 点护甲。若你的生命低于 50%，额外获得 10 点护甲。",
		"card.basic_steady_guard.name": "稳固防御",
		"card.basic_steady_guard.desc": "获得 7 点护甲。若本回合没有打出攻击牌，额外获得 3 点护甲。",
		"card.basic_steady_guard.upgraded_desc": "获得 9 点护甲。若本回合没有打出攻击牌，额外获得 4 点护甲。",
	})
	_add_translations(LANGUAGE_EN, {
		"card.basic_strike.name": "Strike",
		"card.basic_strike.desc": "Deal 4 damage.",
		"card.basic_strike.upgraded_desc": "Deal 9 damage.",
		"card.basic_heavy_blow.name": "Heavy Blow",
		"card.basic_heavy_blow.desc": "Deal 8 damage.",
		"card.basic_heavy_blow.upgraded_desc": "Deal 16 damage.",
		"card.basic_combo_strike.name": "Combo Strike",
		"card.basic_combo_strike.desc": "Deal 3 damage twice.",
		"card.basic_combo_strike.upgraded_desc": "Deal 4 damage twice.",
		"card.basic_flame_slash.name": "Flame Slash",
		"card.basic_flame_slash.desc": "Deal 6 damage and apply 3 Burn.",
		"card.basic_flame_slash.upgraded_desc": "Deal 8 damage and apply 3 Burn.",
		"card.basic_armor_break.name": "Armor Break",
		"card.basic_armor_break.desc": "Deal 6 damage and apply 2 Weak.",
		"card.basic_armor_break.upgraded_desc": "Deal 7 damage and apply 2 Weak.",
		"card.basic_guard.name": "Guard",
		"card.basic_guard.desc": "Gain 5 Block.",
		"card.basic_guard.upgraded_desc": "Gain 8 Block.",
		"card.basic_hold_fast.name": "Hold Fast",
		"card.basic_hold_fast.desc": "Gain 12 Block.",
		"card.basic_hold_fast.upgraded_desc": "Gain 16 Block.",
		"card.basic_nimble_defense.name": "Nimble Defense",
		"card.basic_nimble_defense.desc": "Gain 4 Block and draw 1 card.",
		"card.basic_nimble_defense.upgraded_desc": "Gain 7 Block and draw 1 card.",
		"card.basic_counter_stance.name": "Counter Stance",
		"card.basic_counter_stance.desc": "Gain 6 Block and deal 3 damage.",
		"card.basic_counter_stance.upgraded_desc": "Gain 9 Block and deal 5 damage.",
		"card.basic_iron_wall.name": "Iron Wall",
		"card.basic_iron_wall.desc": "Gain 20 Block.",
		"card.basic_iron_wall.upgraded_desc": "Gain 28 Block.",
		"card.basic_charge.name": "Charge",
		"card.basic_charge.desc": "Gain 1 Energy.",
		"card.basic_charge.upgraded_desc": "Gain 2 Energy.",
		"card.basic_insight.name": "Insight",
		"card.basic_insight.desc": "Draw 2 cards.",
		"card.basic_insight.upgraded_desc": "Draw 3 cards.",
		"card.basic_tactical_shift.name": "Tactical Shift",
		"card.basic_tactical_shift.desc": "Draw 3 cards.",
		"card.basic_tactical_shift.upgraded_desc": "Draw 2 cards.",
		"card.basic_burning_mark.name": "Burning Mark",
		"card.basic_burning_mark.desc": "Apply 4 Burn.",
		"card.basic_burning_mark.upgraded_desc": "Apply 6 Burn.",
		"card.basic_weaken.name": "Weaken",
		"card.basic_weaken.desc": "Apply 4 Weak.",
		"card.basic_weaken.upgraded_desc": "Apply 3 Weak.",
		"card.basic_grace.name": "Grace",
		"card.basic_grace.desc": "Restore 8 HP.",
		"card.basic_restore.name": "Restore",
		"card.basic_restore.desc": "Restore 5 HP.",
		"card.basic_quick_cut.name": "Quick Cut",
		"card.basic_quick_cut.desc": "Deal 3 damage.",
		"card.basic_quick_cut.upgraded_desc": "Deal 5 damage.",
		"card.basic_dual_cut.name": "Dual Cut",
		"card.basic_dual_cut.desc": "Deal 4 damage twice.",
		"card.basic_dual_cut.upgraded_desc": "Deal 5 damage twice.",
		"card.basic_guarded_strike.name": "Guarded Strike",
		"card.basic_guarded_strike.desc": "Deal 5 damage and gain 3 Block.",
		"card.basic_guarded_strike.upgraded_desc": "Deal 7 damage and gain 5 Block.",
		"card.basic_guard_up.name": "Guard Up",
		"card.basic_guard_up.desc": "Gain 3 Block.",
		"card.basic_guard_up.upgraded_desc": "Gain 5 Block.",
		"card.basic_battle_focus.name": "Battle Focus",
		"card.basic_battle_focus.desc": "Draw 1 card and gain 1 Energy.",
		"card.basic_battle_focus.upgraded_desc": "Draw 2 cards and gain 1 Energy.",
		"card.basic_prepare.name": "Prepare",
		"card.basic_prepare.desc": "Draw 1 card, then discard 1 card.",
		"card.basic_prepare.upgraded_desc": "Draw 2 cards, then discard 1 card.",
		"card.basic_cleanse.name": "Cleanse",
		"card.basic_cleanse.desc": "Remove 1 Weak or Burn from yourself and gain 4 Block.",
		"card.basic_cleanse.upgraded_desc": "Remove 1 Weak and 1 Burn from yourself and gain 6 Block.",
		"card.basic_warm_blood.name": "Warm Blood",
		"card.basic_warm_blood.desc": "Restore 3 HP and gain 1 Energy.",
		"card.basic_warm_blood.upgraded_desc": "Restore 5 HP and gain 1 Energy.",
		"card.basic_suppress.name": "Suppress",
		"card.basic_suppress.desc": "Apply 1 Weak. If the enemy has Block, apply 1 additional Weak.",
		"card.basic_suppress.upgraded_desc": "Apply 2 Weak. If the enemy has Block, apply 1 additional Weak.",
		"card.basic_kindling.name": "Kindling",
		"card.basic_kindling.desc": "Apply 2 Burn. If the target has no Burn, apply 4 Burn instead.",
		"card.basic_kindling.upgraded_desc": "Apply 3 Burn. If the target has no Burn, apply 5 Burn instead.",
		"card.basic_flame_guard.name": "Flame Guard",
		"card.basic_flame_guard.desc": "Gain 8 Block and apply 2 Burn.",
		"card.basic_flame_guard.upgraded_desc": "Gain 11 Block and apply 3 Burn.",
		"card.basic_soul_spark.name": "Soul Spark",
		"card.basic_soul_spark.desc": "Deal 2 damage and draw 1 card.",
		"card.basic_soul_spark.upgraded_desc": "Deal 3 damage, draw 1 card, and gain 1 Block.",
		"card.basic_burning_edge.name": "Burning Edge",
		"card.basic_burning_edge.desc": "Deal 5 damage. If the enemy has Burn, deal 3 additional damage.",
		"card.basic_burning_edge.upgraded_desc": "Deal 7 damage. If the enemy has Burn, deal 5 additional damage.",
		"card.basic_cinder_strike.name": "Cinder Strike",
		"card.basic_cinder_strike.desc": "Deal 9 damage. If the enemy has Burn, apply 2 Weak.",
		"card.basic_cinder_strike.upgraded_desc": "Deal 12 damage. If the enemy has Burn, apply 3 Weak.",
		"card.basic_execution.name": "Execution",
		"card.basic_execution.desc": "Deal 10 damage. If the enemy has 50% HP or less, deal 6 additional damage.",
		"card.basic_execution.upgraded_desc": "Deal 13 damage. If the enemy has 50% HP or less, deal 8 additional damage.",
		"card.basic_last_stand.name": "Last Stand",
		"card.basic_last_stand.desc": "Gain 8 Block. If you have 50% HP or less, gain 8 additional Block.",
		"card.basic_last_stand.upgraded_desc": "Gain 10 Block. If you have 50% HP or less, gain 10 additional Block.",
		"card.basic_steady_guard.name": "Steady Guard",
		"card.basic_steady_guard.desc": "Gain 7 Block. If you have not played an Attack card this turn, gain 3 additional Block.",
		"card.basic_steady_guard.upgraded_desc": "Gain 9 Block. If you have not played an Attack card this turn, gain 4 additional Block.",
		"card.curse_fate_mark.name": "Fate Brand",
		"card.curse_fate_mark.desc": "Cannot be played. Stays in your hand and takes up space.",
		"card.major_00_the_fool.name": "The Fool",
		"card.major_00_the_fool.desc": "Draw 3 cards, gain 2 Energy, then discard 1 random card. If it was an Attack, deal 8 extra damage. If it was a Skill, gain 8 extra Block.",
		"card.major_01_the_magician.name": "The Magician",
		"card.major_01_the_magician.desc": "Gain 1 Energy and draw 2 cards. The next non-Magician card you play this turn triggers one additional time.",
		"card.major_02_the_high_priestess.name": "The High Priestess",
		"card.major_02_the_high_priestess.desc": "Draw 3 cards. Those cards cost 1 less this turn.",
		"card.major_03_the_empress.name": "The Empress",
		"card.major_03_the_empress.desc": "Restore 12 HP and gain 12 Block. At the start of your next turn, restore 6 HP.",
		"card.major_04_the_emperor.name": "The Emperor",
		"card.major_04_the_emperor.desc": "Gain 15 Block. At the start of each future player turn, gain 2 extra Block.",
		"card.major_05_the_hierophant.name": "The Hierophant",
		"card.major_05_the_hierophant.desc": "Gain 10 Block and draw 2 cards. The next 2 cards in your hand cost 1 less this turn.",
		"card.major_06_the_lovers.name": "The Lovers",
		"card.major_06_the_lovers.desc": "If you are wounded, restore 12 HP. Otherwise, deal 12 damage.",
		"card.major_07_the_chariot.name": "The Chariot",
		"card.major_07_the_chariot.desc": "Deal 10 damage. If you have already played an Attack this turn, deal 10 extra damage and gain 1 Energy.",
		"card.major_08_strength.name": "Strength",
		"card.major_08_strength.desc": "Your damage is doubled next turn.",
		"card.major_09_the_hermit.name": "The Hermit",
		"card.major_09_the_hermit.desc": "Draw 3 cards. If you have 3 or fewer cards in hand, draw 3 more and gain 1 Energy.",
		"card.major_10_wheel_of_fortune.name": "Wheel of Fortune",
		"card.major_10_wheel_of_fortune.desc": "At the end of each turn, draw 4 cards. If your draw pile is empty before or after drawing, win this battle.",
		"card.major_11_justice.name": "Justice",
		"card.major_11_justice.desc": "Deal damage equal to twice your Block, then keep half your Block. If you have no Block, deal 16 damage and gain 12 Block.",
		"card.major_12_the_hanged_man.name": "The Hanged Man",
		"card.major_12_the_hanged_man.desc": "Lose 5 HP, draw 4 cards, and gain 2 Energy.",
		"card.major_13_death.name": "Death",
		"card.major_13_death.desc": "Apply 4 Weak.",
		"card.major_14_temperance.name": "Temperance",
		"card.major_14_temperance.desc": "Gain 8 Block, restore 3 HP, and draw 2 cards. If you have not played an Attack this turn, gain 2 extra Block.",
		"card.major_15_the_devil.name": "The Devil",
		"card.major_15_the_devil.desc": "Deal 20 damage. At the start of each future player turn, lose 5 HP.",
		"card.major_16_the_tower.name": "The Tower",
		"card.major_16_the_tower.desc": "Remove all enemy Block, deal 15 damage, then lose all your Block.",
		"card.major_17_the_star.name": "The Star",
		"card.major_17_the_star.desc": "Restore 8 HP and draw 1 card. At the start of each future player turn, draw 1 extra card.",
		"card.major_18_the_moon.name": "The Moon",
		"card.major_18_the_moon.desc": "Apply 3 Weak to the enemy and draw 2 cards.",
		"card.major_19_the_sun.name": "The Sun",
		"card.major_19_the_sun.desc": "Apply 4 Burn to the enemy, then double their Burn stacks.",
		"card.major_20_judgement.name": "Judgement",
		"card.major_20_judgement.desc": "Return up to 3 random cards from your discard pile to your hand. They cost 0 this turn.",
		"card.major_21_the_world.name": "The World",
		"card.major_21_the_world.desc": "Deal 16 damage, gain 16 Block, draw 3 cards, gain 2 Energy, and restore 8 HP. If you play 5 or more cards this turn, skip the enemy turn and refill your hand.",
	})


func _install_relic_translations() -> void:
	_add_translations(LANGUAGE_EN, {
		"relic.old_ring.name": "Old Ring",
		"relic.old_ring.desc": "Draw 1 extra card at the start of each battle.",
		"relic.energy_core.name": "Energy Core",
		"relic.energy_core.desc": "Gain 1 extra Energy at the start of each turn.",
		"relic.spiked_charm.name": "Spiked Charm",
		"relic.spiked_charm.desc": "When attacked, reflect 2 damage.",
		"relic.lucky_dice.name": "Lucky Dice",
		"relic.lucky_dice.desc": "Combat rewards show 1 extra card.",
		"relic.warrior_badge.name": "Warrior Badge",
		"relic.warrior_badge.desc": "Attack cards deal +1 damage.",
		"relic.guardian_stone.name": "Guardian Stone",
		"relic.guardian_stone.desc": "Gain 5 Block at the start of each battle.",
		"relic.burning_ember.name": "Burning Ember",
		"relic.burning_ember.desc": "Apply 2 Burn to the enemy at the start of each battle.",
		"relic.swift_boots.name": "Swift Boots",
		"relic.swift_boots.desc": "Draw 2 extra cards on the first turn.",
		"relic.fate_ember.name": "Fate Ember",
		"relic.fate_ember.desc": "When you fall in battle, this relic is consumed to fully restore your HP and retry the current encounter.",
	})


func _install_enemy_translations() -> void:
	_add_translations(LANGUAGE_EN, {
		"enemy.slime.name": "Slime",
		"enemy.goblin.name": "Goblin",
		"enemy.forest_wolf.name": "Forest Wolf",
		"enemy.poison_vine.name": "Poison Vine",
		"enemy.mushroom_mage.name": "Mushroom Mage",
		"enemy.ancient_treant.name": "Ancient Treant",
		"enemy.berserker_orc.name": "Berserker Orc",
		"enemy.forest_guardian.name": "Forest Guardian",
		"enemy.fire_elemental.name": "Fire Elemental",
		"enemy.lava_slime.name": "Lava Slime",
		"enemy.flame_archer.name": "Flame Archer",
		"enemy.lava_guard.name": "Lava Guard",
		"enemy.ash_mage.name": "Ash Mage",
		"enemy.molten_knight.name": "Molten Knight",
		"enemy.blazing_golem.name": "Blazing Golem",
		"enemy.molten_lord.name": "Molten Lord",
		"enemy.astral_wraith.name": "Astral Wraith",
		"enemy.void_walker.name": "Void Walker",
		"enemy.mirror_golem.name": "Mirror Golem",
		"enemy.shadow_priest.name": "Shadow Priest",
		"enemy.time_guardian.name": "Time Guardian",
		"enemy.fate_judge.name": "Fate Judge",
		"enemy.astral_drake.name": "Astral Drake",
		"enemy.world_devourer.name": "World Devourer",
		"enemy.fate_echo.name": "Fate Echo",
		"enemy.rift_spirit.name": "Rift Spirit",
		"enemy.eclipse_acolyte.name": "Eclipse Acolyte",
		"enemy.fate_stitcher.name": "Fate Stitcher",
		"enemy.rift_enforcer.name": "Rift Enforcer",
		"enemy.astral_judicator.name": "Astral Judicator",
		"enemy.abyss_avatar.name": "Abyss Avatar",
	})


func _install_localization_gap_translations() -> void:
	_add_translations(LANGUAGE_ZH, {
		"ui_choose": "选择",
		"ui_skip": "跳过",
		"ui_price_gold": "价格：{price} 金币",
		"ui_current_gold": "金币：{gold}",
		"ui_gain_gold": "获得 {amount} 金币。",
		"ui_spend_gold": "花费 {amount} 金币。",
		"ui_not_enough_gold": "金币不足",
		"ui_not_enough_hp": "生命不足",
		"ui_no_available": "暂无可用内容",
		"map_no_active_run": "当前没有进行中的冒险，请先开始新游戏。",
		"map_node_unavailable": "这个节点还不能前往",
		"deck_view.full": "全部牌组（{count}）",
		"deck_view.draw": "抽牌堆（{count}）",
		"deck_view.discard": "弃牌堆（{count}）",
		"deck_view.exhaust": "消耗牌堆（{count}）",
		"reward_no_active_title": "没有进行中的冒险",
		"reward_no_active_desc": "请从主菜单开始新游戏或继续游戏。",
		"reward_gold_title": "金币奖励",
		"reward_no_card_desc": "本场战斗没有可获得的普通卡牌。",
		"reward_added_collection": "已加入你的卡牌仓库。",
		"reward_gold_line": "获得金币：+{reward}\n当前金币：{current}",
		"relic_reward_take": "获取",
		"relic_reward_all_collected": "遗物已收集完成",
		"relic_reward_all_collected_desc": "当前没有新的遗物可获得。",
		"rest_invalid_node": "当前节点不是休息点。",
		"rest_used": "这个休息点已经使用过。",
		"rest_resume_used": "已选择休息点效果，请点击继续。",
		"rest_choose_prompt": "选择一项：恢复生命，或强化当前卡组中的一张基础牌。",
		"rest_healed": "已恢复生命（+{amount}）",
		"rest_no_upgrade_cards": "当前卡组没有可强化的基础牌。",
		"rest_choose_upgrade": "选择一张基础牌进行强化。",
		"rest_cannot_upgrade": "这张牌无法强化。",
		"rest_upgraded": "已强化：{card}",
		"rest_health": "生命：{current} / {max}",
		"battle_return_confirm_title": "确认返回主菜单",
		"battle_return_confirm_message": "当前战斗进度会保留到存档状态，确定返回主菜单吗？",
		"battle_float_heal": "+{amount} 生命",
		"battle_float_block": "+{amount} 护甲",
		"battle_float_guard": "格挡 {amount}",
		"battle_float_burn": "燃烧 +{amount}",
		"battle_float_weak": "虚弱 +{amount}",
		"battle_draw_failed_empty": "抽牌堆和弃牌堆都为空，无法继续抽牌。",
		"effect_damage": "造成 {value} 点伤害",
		"effect_damage_times": "造成 {value} 点伤害 x{times}",
		"effect_block": "获得 {value} 点护甲",
		"effect_energy": "获得 {value} 点能量",
		"effect_draw": "抽 {value} 张牌",
		"effect_draw_overflow": "抽 {value} 张牌，摧毁 {destroyed} 张溢出牌",
		"effect_heal": "回复 {value} 点生命",
		"effect_apply_burn": "施加 {value} 层燃烧",
		"effect_apply_weak": "施加 {value} 层虚弱",
		"effect_remove_burn": "移除燃烧",
		"effect_remove_weak": "移除虚弱",
		"effect_cleanse": "净化负面状态",
		"effect_cleanse_none": "没有可净化的负面状态",
		"effect_cleanse_result": "净化：虚弱 {weak} / 燃烧 {burn}",
		"effect_discard": "弃 {value} 张牌",
		"effect_discard_named": "弃掉 {cards}",
		"effect_discard_none": "没有弃牌",
		"effect_shuffle": "洗牌",
		"effect_no_effect": "没有效果",
		"effect_battle_ended": "战斗已结束",
		"effect_condition_not_met": "条件未满足",
		"effect_bonus_damage": "额外造成 {value} 点伤害",
		"effect_bonus_block": "额外获得 {value} 点护甲",
		"effect_next_turn_double_damage": "下回合造成的伤害翻倍",
		"effect_activate_wheel": "激活命运之轮",
		"effect_reduce_next_cost": "降低接下来卡牌费用",
		"effect_retained_block_damage": "造成 {damage} 点伤害，保留一半护甲",
		"effect_remove_all_block_damage": "移除双方护甲，造成 {damage} 点伤害",
		"effect_recover_discard_zero": "从弃牌堆取回 {count} 张牌，并使费用变为 0",
		"effect_overflow_suffix": "，摧毁 {count} 张溢出牌",
		"effect_play_card_log": "打出 {card}：{effects}",
		"effect_not_enough_energy": "{card} 的能量不足。",
		"effect_magician_double": "魔术师：效果重复触发！",
		"effect_wheel_turn_draw": "命运之轮抽 4 张牌。",
		"effect_world_skip_enemy": "世界跳过敌人回合，并把手牌补满。",
		"effect_fate_ember_revive": "命运余烬燃尽，你重新站了起来。",
		"effect_fate_ember_banner": "命运余烬燃尽！",
		"effect_fate_ember_float": "命运余烬：复活",
		"effect_fool_attack": "抽 3 张牌，获得 2 点能量，弃掉 {card}，额外造成 {damage} 点伤害{overflow}",
		"effect_fool_skill": "抽 3 张牌，获得 2 点能量，弃掉 {card}，额外获得 8 点护甲{overflow}",
		"effect_fool": "抽 3 张牌，获得 2 点能量{overflow}",
		"effect_magician": "获得 1 点能量，抽 2 张牌。本回合下一张非魔术师卡牌额外触发一次{overflow}",
		"effect_high_priestess": "抽 3 张牌，本回合抽到的牌费用减少 1{overflow}",
		"effect_hermit_big": "抽 6 张牌，获得 1 点能量{overflow}",
		"effect_hermit": "抽 3 张牌{overflow}",
		"effect_hanged_man": "失去 5 点生命，抽 4 张牌，获得 2 点能量{overflow}",
		"effect_temperance_bonus": "获得 10 点护甲，回复 3 点生命，抽 2 张牌{overflow}",
		"effect_temperance": "获得 8 点护甲，回复 3 点生命，抽 2 张牌{overflow}",
		"effect_devil": "造成 {damage} 点伤害，每回合开始受到 5 点伤害",
		"effect_star": "回复 8 点生命，抽 1 张牌，之后每回合额外抽 1 张{overflow}",
		"effect_sun": "施加 4 层燃烧，并使燃烧层数翻倍",
		"effect_world": "造成 {damage} 点伤害，获得 16 点护甲，抽 3 张牌，获得 2 点能量，回复 8 点生命{overflow}",
		"effect_empress": "回复 12 点生命，获得 12 点护甲，下回合回复 6 点生命",
		"effect_emperor": "获得 15 点护甲，之后每回合额外获得 2 点护甲",
		"effect_hierophant": "获得 10 点护甲，抽 2 张牌，降低接下来卡牌费用{overflow}",
		"battle_turn_start_player": "玩家回合开始",
		"battle_turn_start_enemy": "敌人回合开始",
		"battle_turn_draw_cards": "抽 {value} 张牌",
		"battle_turn_count_player": "第 {turn} 回合｜玩家回合",
		"battle_turn_count_enemy": "第 {turn} 回合｜敌人回合",
		"intent.attack": "攻击 {value}",
		"intent.attack_times": "攻击 {value} x{times}",
		"intent.strong_attack": "强力攻击 {value}",
		"intent.block": "防御 {value}",
		"intent.apply_burn": "燃烧 {value}",
		"intent.apply_weak": "虚弱 {value}",
		"intent.block_weak": "防御 {value} / 虚弱",
		"intent.buff": "强化 +{value}",
		"intent.charge": "蓄力",
		"intent.heal": "治疗 {value}",
		"intent.unknown": "未知",
		"status.none": "无",
		"boss_mechanic.ancient_wrath": "古树之怒",
		"boss_mechanic.molten_fury": "熔火狂怒",
		"boss_mechanic.doom_countdown": "终焉倒计时",
		"boss_mechanic.astral_judgment": "星律审判",
		"boss_mechanic.abyssal_corruption": "深渊侵蚀",
		"boss_mechanic.generic": "Boss 之力",
		"boss_mechanic.forest_inactive": "{mechanic} x0：每损失 50 生命，攻击伤害 +2",
		"boss_mechanic.stacks_attack": "{mechanic} x{stacks}：攻击 +{bonus}",
		"boss_mechanic.molten_active": "{mechanic}：攻击 +5",
		"boss_mechanic.molten_inactive": "{mechanic}：生命低于 50% 后攻击 +5",
		"boss_mechanic.doom_bonus": "{mechanic} x{stacks}：攻击 +{bonus}，下一次攻击额外 +15",
		"boss_mechanic.astral_note": "{mechanic} x{stacks}：攻击 +{bonus}",
		"boss_mechanic.abyss_note": "{mechanic} x{stacks}：攻击 +{bonus}",
		"boss_mechanic_trigger": "{mechanic} 触发！",
		"boss_mechanic_progress": "{mechanic} 推进！",
		"boss_mechanic_gain": "{mechanic} +{amount}",
		"boss_mechanic_active": "{mechanic} 激活",
		"enemy_action.attack": "{enemy} 攻击造成 {value} 点伤害。",
		"enemy_action.attack_times": "{enemy} 攻击造成 {value} 点伤害 x{times}。",
		"enemy_action.strong_attack": "{enemy} 强力攻击造成 {value} 点伤害。",
		"enemy_action.strong_attack_times": "{enemy} 强力攻击造成 {value} 点伤害 x{times}。",
		"enemy_action.block": "{enemy} 获得 {value} 点护甲。",
		"enemy_action.strength": "{enemy} 获得 {value} 点力量。",
		"enemy_action.apply_weak": "{enemy} 施加 {value} 层虚弱。",
		"enemy_action.apply_burn": "{enemy} 施加 {value} 层燃烧。",
		"enemy_action.block_weak": "{enemy} 获得 {block} 点护甲，并施加 {weak} 层虚弱。",
		"enemy_action.charge": "{enemy} 正在蓄力。",
		"enemy_action.heal": "{enemy} 回复 {value} 点生命。",
		"enemy_action.none": "{enemy} 没有行动。",
		"difficulty_highest_completed": "你已完成最高难度挑战",
		"difficulty_unlocked_new": "已解锁新难度：{difficulty}",
		"difficulty_already_completed": "当前难度已通关",
		"event.effect_heal": "恢复 {amount} 点生命。",
		"event.effect_lose_hp": "失去 {amount} 点生命。",
		"event.effect_gain_basic": "获得基础牌：{card}。",
		"event.effect_gain_special": "获得特殊卡牌：{card}。",
		"event.effect_gain_relic": "获得遗物：{relic}。",
		"event.effect_upgrade": "已强化：{card}。",
		"event.effect_remove": "已移除：{card}。",
		"event.effect_add_curse": "加入诅咒牌：{card}。",
		"event.effect_no_basic": "没有可获得的基础牌。",
		"event.effect_no_special": "特殊卡牌已收集完。",
		"event.effect_no_relic": "遗物已收集完。",
		"event.effect_no_upgrade": "没有可强化的基础牌。",
		"event.effect_no_remove": "没有可移除的基础牌。",
		"event.effect_fate_light": "命运偏向星辰。",
		"event.effect_fate_dark": "命运偏向深渊。",
		"event.effect_fate_change": "命运轨迹发生了变化。",
		"event.effect_unlock_star": "星辰路线已解锁。",
		"event.effect_unlock_abyss": "深渊路线已解锁。",
		"event.effect_random_risk_safe": "裂隙试图撕裂你，但你勉强避开了致命伤害。",
		"event.effect_curse_missing": "TODO：诅咒牌数据缺失，本次没有加入诅咒牌。",
	})
	_add_translations(LANGUAGE_EN, {
		"ui_choose": "Choose",
		"ui_skip": "Skip",
		"ui_price_gold": "Price: {price} Gold",
		"ui_current_gold": "Gold: {gold}",
		"ui_gain_gold": "Gain {amount} Gold.",
		"ui_spend_gold": "Spend {amount} Gold.",
		"ui_not_enough_gold": "Not enough gold",
		"ui_not_enough_hp": "Not enough HP",
		"ui_no_available": "Nothing available",
		"map_no_active_run": "No adventure in progress. Start a new game first.",
		"map_node_unavailable": "This node is not available yet.",
		"deck_view.full": "Full Deck ({count})",
		"deck_view.draw": "Draw Pile ({count})",
		"deck_view.discard": "Discard Pile ({count})",
		"deck_view.exhaust": "Exhaust Pile ({count})",
		"reward_no_active_title": "No Adventure in Progress",
		"reward_no_active_desc": "Start a new game or continue from the main menu.",
		"reward_gold_title": "Gold Reward",
		"reward_no_card_desc": "No basic card reward is available from this battle.",
		"reward_added_collection": "Added to your card collection.",
		"reward_gold_line": "Gold gained: +{reward}\nCurrent Gold: {current}",
		"relic_reward_take": "Take",
		"relic_reward_all_collected": "All Relics Collected",
		"relic_reward_all_collected_desc": "There are no new relics to gain.",
		"rest_invalid_node": "The current node is not a rest site.",
		"rest_used": "This rest site has already been used.",
		"rest_resume_used": "A rest option has already been chosen. Press Continue.",
		"rest_choose_prompt": "Choose one: recover HP, or upgrade one basic card in your deck.",
		"rest_healed": "Recovered HP (+{amount})",
		"rest_no_upgrade_cards": "Your current deck has no upgradeable basic cards.",
		"rest_choose_upgrade": "Choose a basic card to upgrade.",
		"rest_cannot_upgrade": "This card cannot be upgraded.",
		"rest_upgraded": "Upgraded: {card}",
		"rest_health": "HP: {current} / {max}",
		"battle_return_confirm_title": "Return to Main Menu",
		"battle_return_confirm_message": "Your current combat progress will remain in the saved run state. Return to the main menu?",
		"battle_float_heal": "+{amount} HP",
		"battle_float_block": "+{amount} Block",
		"battle_float_guard": "Guard {amount}",
		"battle_float_burn": "Burn +{amount}",
		"battle_float_weak": "Weak +{amount}",
		"battle_draw_failed_empty": "Both draw and discard piles are empty. You cannot draw any more cards.",
		"effect_damage": "Deal {value} damage",
		"effect_damage_times": "Deal {value} damage x{times}",
		"effect_block": "Gain {value} Block",
		"effect_energy": "Gain {value} Energy",
		"effect_draw": "Draw {value} card(s)",
		"effect_draw_overflow": "Draw {value} card(s), destroyed {destroyed} overflow card(s)",
		"effect_heal": "Heal {value} HP",
		"effect_apply_burn": "Apply {value} Burn",
		"effect_apply_weak": "Apply {value} Weak",
		"effect_remove_burn": "Remove Burn",
		"effect_remove_weak": "Remove Weak",
		"effect_cleanse": "Cleanse negative status",
		"effect_cleanse_none": "No negative status to cleanse",
		"effect_cleanse_result": "Cleansed: Weak {weak} / Burn {burn}",
		"effect_discard": "Discard {value} card(s)",
		"effect_discard_named": "Discarded {cards}",
		"effect_discard_none": "Discarded no cards",
		"effect_shuffle": "Shuffle",
		"effect_no_effect": "No effect",
		"effect_battle_ended": "Battle ended",
		"effect_condition_not_met": "Condition not met",
		"effect_bonus_damage": "Deal {value} bonus damage",
		"effect_bonus_block": "Gain {value} bonus Block",
		"effect_next_turn_double_damage": "Double your damage next turn",
		"effect_activate_wheel": "Activate Wheel of Fortune",
		"effect_reduce_next_cost": "Reduce the cost of upcoming cards",
		"effect_retained_block_damage": "Deal {damage} damage and retain half your Block",
		"effect_remove_all_block_damage": "Remove all Block and deal {damage} damage",
		"effect_recover_discard_zero": "Recover {count} card(s) from discard and set their cost to 0",
		"effect_overflow_suffix": ", destroyed {count} overflow card(s)",
		"effect_play_card_log": "Played {card}: {effects}",
		"effect_not_enough_energy": "Not enough energy for {card}.",
		"effect_magician_double": "The Magician: effect triggers again!",
		"effect_wheel_turn_draw": "Wheel of Fortune draws 4 cards.",
		"effect_world_skip_enemy": "The World skips the enemy turn and refills your hand.",
		"effect_fate_ember_revive": "Fate Ember burns out. You rise again.",
		"effect_fate_ember_banner": "Fate Ember burns out!",
		"effect_fate_ember_float": "Fate Ember: Revive",
		"effect_fool_attack": "Draw 3 cards, gain 2 Energy, discard {card}, and deal {damage} bonus damage{overflow}",
		"effect_fool_skill": "Draw 3 cards, gain 2 Energy, discard {card}, and gain 8 bonus Block{overflow}",
		"effect_fool": "Draw 3 cards and gain 2 Energy{overflow}",
		"effect_magician": "Gain 1 Energy and draw 2 cards. The next non-Magician card you play this turn triggers one additional time{overflow}",
		"effect_high_priestess": "Draw 3 cards. Cards drawn this turn cost 1 less{overflow}",
		"effect_hermit_big": "Draw 6 cards and gain 1 Energy{overflow}",
		"effect_hermit": "Draw 3 cards{overflow}",
		"effect_hanged_man": "Lose 5 HP, draw 4 cards, and gain 2 Energy{overflow}",
		"effect_temperance_bonus": "Gain 10 Block, heal 3 HP, and draw 2 cards{overflow}",
		"effect_temperance": "Gain 8 Block, heal 3 HP, and draw 2 cards{overflow}",
		"effect_devil": "Deal {damage} damage. Take 5 damage at the start of each turn",
		"effect_star": "Heal 8 HP and draw 1 card. Draw 1 extra card each turn afterward{overflow}",
		"effect_sun": "Apply 4 Burn, then double Burn stacks",
		"effect_world": "Deal {damage} damage, gain 16 Block, draw 3 cards, gain 2 Energy, and heal 8 HP{overflow}",
		"effect_empress": "Heal 12 HP, gain 12 Block, and heal 6 HP next turn",
		"effect_emperor": "Gain 15 Block, then gain 2 extra Block each turn",
		"effect_hierophant": "Gain 10 Block, draw 2 cards, and reduce the cost of upcoming cards{overflow}",
		"battle_turn_start_player": "Player Turn Start",
		"battle_turn_start_enemy": "Enemy Turn Start",
		"battle_turn_draw_cards": "Draw {value} cards",
		"battle_turn_count_player": "Turn {turn} | Player Turn",
		"battle_turn_count_enemy": "Turn {turn} | Enemy Turn",
		"intent.attack": "Attack {value}",
		"intent.attack_times": "Attack {value} x{times}",
		"intent.strong_attack": "Strong {value}",
		"intent.block": "Block {value}",
		"intent.apply_burn": "Burn {value}",
		"intent.apply_weak": "Weak {value}",
		"intent.block_weak": "Block {value} / Weak",
		"intent.buff": "Buff +{value}",
		"intent.charge": "Charge",
		"intent.heal": "Heal {value}",
		"intent.unknown": "Unknown",
		"status.none": "None",
		"boss_mechanic.ancient_wrath": "Ancient Wrath",
		"boss_mechanic.molten_fury": "Molten Fury",
		"boss_mechanic.doom_countdown": "Doom Countdown",
		"boss_mechanic.astral_judgment": "Astral Judgment",
		"boss_mechanic.abyssal_corruption": "Abyssal Corruption",
		"boss_mechanic.generic": "Boss Power",
		"boss_mechanic.forest_inactive": "{mechanic} x0: +2 attack whenever 50 HP is lost",
		"boss_mechanic.stacks_attack": "{mechanic} x{stacks}: Attack +{bonus}",
		"boss_mechanic.molten_active": "{mechanic}: Attack +5",
		"boss_mechanic.molten_inactive": "{mechanic}: Attack +5 below 50% HP",
		"boss_mechanic.doom_bonus": "{mechanic} x{stacks}: Attack +{bonus}, next attack +15",
		"boss_mechanic.astral_note": "{mechanic} x{stacks}: Attack +{bonus}",
		"boss_mechanic.abyss_note": "{mechanic} x{stacks}: Attack +{bonus}",
		"boss_mechanic_trigger": "{mechanic} triggered!",
		"boss_mechanic_progress": "{mechanic} advances!",
		"boss_mechanic_gain": "{mechanic} +{amount}",
		"boss_mechanic_active": "{mechanic} active",
		"enemy_action.attack": "{enemy} attacked for {value}.",
		"enemy_action.attack_times": "{enemy} attacked for {value} x{times}.",
		"enemy_action.strong_attack": "{enemy} used a strong attack for {value}.",
		"enemy_action.strong_attack_times": "{enemy} used a strong attack for {value} x{times}.",
		"enemy_action.block": "{enemy} gained {value} Block.",
		"enemy_action.strength": "{enemy} gained {value} Strength.",
		"enemy_action.apply_weak": "{enemy} applied {value} Weak.",
		"enemy_action.apply_burn": "{enemy} applied {value} Burn.",
		"enemy_action.block_weak": "{enemy} gained {block} Block and applied {weak} Weak.",
		"enemy_action.charge": "{enemy} is charging.",
		"enemy_action.heal": "{enemy} healed {value} HP.",
		"enemy_action.none": "{enemy} did nothing.",
		"difficulty_highest_completed": "You have completed the highest difficulty.",
		"difficulty_unlocked_new": "New difficulty unlocked: {difficulty}",
		"difficulty_already_completed": "This difficulty has already been cleared.",
		"event.effect_heal": "Restore {amount} HP.",
		"event.effect_lose_hp": "Lose {amount} HP.",
		"event.effect_gain_basic": "Gained basic card: {card}.",
		"event.effect_gain_special": "Gained special card: {card}.",
		"event.effect_gain_relic": "Gained relic: {relic}.",
		"event.effect_upgrade": "Upgraded: {card}.",
		"event.effect_remove": "Removed: {card}.",
		"event.effect_add_curse": "Added curse card: {card}.",
		"event.effect_no_basic": "No basic card is available.",
		"event.effect_no_special": "All special cards have been collected.",
		"event.effect_no_relic": "All relics have been collected.",
		"event.effect_no_upgrade": "No upgradeable basic card is available.",
		"event.effect_no_remove": "No removable basic card is available.",
		"event.effect_fate_light": "Fate leans toward starlight.",
		"event.effect_fate_dark": "Fate leans toward the abyss.",
		"event.effect_fate_change": "The course of fate shifts.",
		"event.effect_unlock_star": "Starlight route unlocked.",
		"event.effect_unlock_abyss": "Abyss route unlocked.",
		"event.effect_random_risk_safe": "The rift tries to tear you apart, but you barely avoid fatal harm.",
		"event.effect_curse_missing": "TODO: Curse card data is missing. No curse was added this time.",
	})
	_install_event_translations()


func _install_event_translations() -> void:
	var zh_events := {
		"fate_crossroads": ["命运岔路", "星光与深渊在你的面前分成两条道路，等待你作出选择。", "接受星辰的指引", "聆听深渊的低语", "保持沉默", "温柔的星光照亮了你的道路。", "黑暗中的声音记住了你的名字。", "你没有回应任何一方。"],
		"star_whisper": ["星辰低语", "夜空中，一颗星辰向你低语，仿佛在指引你走向某种命运。", "接受星辰的指引", "拒绝指引", "亵渎星辰", "星光在你的掌心凝聚，命运的丝线重新排列。你感觉到，某条隐藏的道路已经向你敞开。", "你低下头，继续前进。星辰的声音逐渐远去。", "星光熄灭了一瞬，你的口袋变沉了，但胸口传来刺痛。"],
		"abyss_contract": ["深渊契约", "裂隙中伸出一只漆黑的手，向你递来一份燃烧的契约。", "签下契约", "烧毁契约", "离开", "契约化作黑色灰烬烙入你的灵魂。深渊回应了你的欲望，一条不应存在的道路在远方裂开。", "黑色火焰吞噬了契约，你的意志经受了考验。", "你没有回应深渊的邀请。"],
		"fate_scales": ["命运天平", "一座巨大的天平悬浮在道路中央，一端放着金币，另一端放着鲜血。", "献出金币（80）", "献出生命（15）", "打碎天平", "天平向星光倾斜，你的卡牌获得了新的力量。", "天平向阴影倾斜，一张塔罗牌从血色雾气中浮现。", "天平碎裂，命运发出刺耳的尖啸。"],
		"shattered_mirror_hall": ["破碎镜厅", "你走进一间由无数镜子组成的大厅。镜中的自己似乎比你更强，也更危险。", "直视镜像", "打碎镜子", "闭眼通过", "镜中的自己露出微笑，你获得了力量，也付出了代价。", "碎片中流出黑雾，金币散落在地。", "你没有看见镜中之物，也没有被它看见。"],
		"corrupted_shrine": ["被污染的圣坛", "这座圣坛曾经神圣，如今却被黑色藤蔓缠绕。", "净化圣坛", "吸收污染", "绕开", "圣坛重新亮起，你却感到身体被掏空了一部分。", "污染化作财富，但某种东西也随之进入了你的牌组。", "你决定不干涉这片污秽之地。"],
		"unstable_portal": ["失控传送门", "一道不稳定的传送门正在撕裂空间，里面闪烁着未知的奖励。", "进入传送门", "稳定传送门（50）", "破坏传送门", "你穿过裂隙，命运在另一侧等待着你。", "传送门逐渐稳定，一股暖流包裹了你。", "传送门爆裂，金币从裂隙中坠落。"],
		"mystic_spring": ["神秘泉水", "你在遗迹深处发现了一口散发微光的泉水。", "饮用泉水", "投入金币（30）", "离开", "清凉的泉水治愈了你的伤口。", "泉水回应了你的供奉，一个遗物浮出水面。", "你决定不冒险。"],
		"wandering_merchant": ["流浪商人", "一个神秘商人拦住了你的去路，提出一笔交易。", "购买普通卡牌（40）", "购买塔罗线索（100）", "拒绝交易", "你获得了一张新的基础牌。", "你获得了一张特殊卡牌。", "商人耸耸肩，消失在阴影中。"],
		"broken_altar": ["破碎祭坛", "一座古老祭坛仍残留着强大的魔力。", "献祭生命（10）", "净化祭坛", "离开", "祭坛吸收了你的鲜血，并赐予你力量。", "祭坛中的残余魔力化作金币。", "你没有触碰这座危险的祭坛。"],
		"forgotten_blacksmith": ["遗忘铁匠", "一名沉默的铁匠愿意为你强化装备。", "强化一张基础牌", "支付金币强化（50）", "离开", "铁匠强化了你的卡牌。", "金币换来了更强的力量。", "铁匠继续敲打他的铁砧。"],
		"cursed_chest": ["被诅咒的宝箱", "一个黑色宝箱静静躺在路边，散发着不祥的气息。", "打开宝箱", "谨慎打开", "离开", "你获得了金币，但诅咒缠上了你。", "你只拿走了表面的金币。", "你决定不碰这个箱子。"],
		"star_divination": ["星象占卜", "一位占星师为你展开星图，命运的轨迹逐渐清晰。", "占卜未来（50）", "调整命运", "拒绝占卜", "你窥见了命运的一角。", "一张卡牌从你的命运中消失了。", "你不愿窥探未来。"],
	}
	var en_events := {
		"fate_crossroads": ["Crossroads of Fate", "Starlight and abyss split into two paths before you, waiting for your choice.", "Accept the stars' guidance", "Listen to the abyss", "Remain silent", "Gentle starlight illuminates your road.", "The voice in the dark remembers your name.", "You answer neither side."],
		"star_whisper": ["Star Whisper", "A star whispers to you from the night sky, as if guiding you toward a certain fate.", "Accept the guidance", "Refuse the guidance", "Profane the star", "Starlight gathers in your palm, and threads of fate rearrange. You feel a hidden road open before you.", "You lower your head and continue. The star's voice fades away.", "The starlight dies for a moment. Your pouch grows heavier, but pain stabs through your chest."],
		"abyss_contract": ["Abyssal Contract", "A blackened hand reaches from a rift, offering you a burning contract.", "Sign the contract", "Burn the contract", "Leave", "The contract becomes black ash branded into your soul. The abyss answers your desire, and a forbidden road opens in the distance.", "Black flame devours the contract. Your will is tested.", "You do not answer the invitation of the abyss."],
		"fate_scales": ["Scales of Fate", "A vast set of scales floats in the road. Gold rests on one side, blood on the other.", "Offer gold (80)", "Offer life (15)", "Break the scales", "The scales tip toward starlight, and your cards gain new strength.", "The scales tip toward shadow, and a tarot card rises from blood-red mist.", "The scales shatter. Fate screams in your ears."],
		"shattered_mirror_hall": ["Shattered Mirror Hall", "You enter a hall of countless mirrors. Your reflection seems stronger than you, and more dangerous.", "Face the reflection", "Shatter the mirrors", "Pass with eyes closed", "Your reflection smiles. You gain power, and pay the price.", "Black fog leaks from the shards, and gold scatters across the floor.", "You do not see the thing in the mirror, and it does not see you."],
		"corrupted_shrine": ["Corrupted Shrine", "This shrine was once holy, but black vines now coil around it.", "Purify the shrine", "Absorb the corruption", "Go around", "The shrine lights again, though you feel hollowed out.", "The corruption becomes wealth, but something enters your deck with it.", "You decide not to disturb this tainted place."],
		"unstable_portal": ["Unstable Portal", "An unstable portal tears at space, flashing with unknown rewards.", "Enter the portal", "Stabilize the portal (50)", "Destroy the portal", "You pass through the rift. Fate waits on the other side.", "The portal steadies, and warmth surrounds you.", "The portal bursts, spilling gold from the rift."],
		"mystic_spring": ["Mystic Spring", "Deep in the ruins, you find a spring glowing with faint light.", "Drink from the spring", "Offer gold (30)", "Leave", "The cool water heals your wounds.", "The spring answers your offering, and a relic rises from the water.", "You decide not to risk it."],
		"wandering_merchant": ["Wandering Merchant", "A mysterious merchant blocks your path and offers a trade.", "Buy a basic card (40)", "Buy a tarot clue (100)", "Refuse the trade", "You gain a new basic card.", "You gain a special card.", "The merchant shrugs and vanishes into shadow."],
		"broken_altar": ["Broken Altar", "An ancient altar still holds powerful magic.", "Sacrifice life (10)", "Purify the altar", "Leave", "The altar drinks your blood and grants you power.", "The altar's remaining magic turns into gold.", "You do not touch the dangerous altar."],
		"forgotten_blacksmith": ["Forgotten Blacksmith", "A silent blacksmith is willing to strengthen your equipment.", "Upgrade a basic card", "Pay for an upgrade (50)", "Leave", "The blacksmith upgrades your card.", "Gold buys you greater strength.", "The blacksmith keeps hammering his anvil."],
		"cursed_chest": ["Cursed Chest", "A black chest lies quietly by the road, radiating ill omen.", "Open the chest", "Open carefully", "Leave", "You gain gold, but the curse clings to you.", "You take only the gold on the surface.", "You decide not to touch the chest."],
		"star_divination": ["Star Divination", "An astrologer unfolds a star chart for you. The path of fate becomes clear.", "Divine the future (50)", "Adjust fate", "Refuse divination", "You glimpse a corner of fate.", "A card disappears from your destiny.", "You refuse to peer into the future."],
	}
	_install_event_dictionary(LANGUAGE_ZH, zh_events)
	_install_event_dictionary(LANGUAGE_EN, en_events)


func _install_event_dictionary(language: String, events: Dictionary) -> void:
	var entries := {}
	for event_id in events.keys():
		var values: Array = events[event_id] as Array
		entries["event.%s.title" % event_id] = values[0]
		entries["event.%s.desc" % event_id] = values[1]
		for index in range(3):
			entries["event.%s.choice_%d" % [event_id, index + 1]] = values[2 + index]
			entries["event.%s.result_%d" % [event_id, index + 1]] = values[5 + index]
	_add_translations(language, entries)
